#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-or-later
"""Pre-renders a font atlas for the PC preview of the BedrockLink GUI.

The Switch build draws text with the console's system font (SDL2_ttf). The PC
preview has no SDL2_ttf, so it draws from this atlas instead: Latin-1 glyphs at the
four sizes the GUI uses, from a similar sans-serif font installed on the PC.

Usage: tools/make_font_atlas.py <font.ttf> <out_dir>   -> font_atlas.bin, font_atlas.h
"""
import sys
from PIL import Image, ImageFont

SIZES = [19, 23, 28, 40]          # FONT_S, FONT_M, FONT_L, FONT_XL in gfx.h
CODES = list(range(32, 127)) + list(range(160, 256))
ATLAS_W = 1024


def main():
    font_path, out = sys.argv[1], sys.argv[2]
    glyphs, line_h = [], []
    x = y = row_h = 0
    pieces = []
    for fi, px in enumerate(SIZES):
        font = ImageFont.truetype(font_path, px)
        ascent, descent = font.getmetrics()
        line_h.append(ascent + descent)
        table = {}
        for code in CODES:
            ch = chr(code)
            adv = round(font.getlength(ch))
            bbox = font.getbbox(ch, anchor="la")
            w, h = bbox[2] - bbox[0], bbox[3] - bbox[1]
            if w <= 0 or h <= 0:
                table[code] = (0, 0, 0, 0, 0, 0, adv)
                continue
            img = Image.new("L", (w, h), 0)
            from PIL import ImageDraw
            ImageDraw.Draw(img).text((-bbox[0], -bbox[1]), ch, font=font, fill=255, anchor="la")
            if x + w + 1 > ATLAS_W:
                x, y, row_h = 0, y + row_h + 1, 0
            pieces.append((img, x, y))
            table[code] = (x, y, w, h, bbox[0], bbox[1], adv)
            x += w + 1
            row_h = max(row_h, h)
        glyphs.append(table)
    atlas_h = y + row_h + 1
    atlas = Image.new("L", (ATLAS_W, atlas_h), 0)
    for img, px_, py in pieces:
        atlas.paste(img, (px_, py))
    with open(f"{out}/font_atlas.bin", "wb") as f:
        f.write(atlas.tobytes())
    with open(f"{out}/font_atlas.h", "w") as f:
        f.write("// Generated by tools/make_font_atlas.py - PC preview only.\n")
        f.write(f"#define ATLAS_W {ATLAS_W}\n#define ATLAS_H {atlas_h}\n")
        f.write("typedef struct { short x, y, w, h, ox, oy, adv; } atlas_glyph;\n")
        f.write("static const int atlas_line_h[%d] = {%s};\n" % (len(SIZES), ", ".join(map(str, line_h))))
        f.write("static const atlas_glyph atlas_glyphs[%d][256] = {\n" % len(SIZES))
        for table in glyphs:
            f.write("  {")
            f.write(", ".join("[%d] = {%s}" % (c, ", ".join(map(str, table[c]))) for c in CODES))
            f.write("},\n")
        f.write("};\n")
    print(f"atlas {ATLAS_W}x{atlas_h}, {len(CODES)} glyphs x {len(SIZES)} sizes")


if __name__ == "__main__":
    main()
